name: Backlog Issue Status Update

on:
  pull_request:
    types: [closed, opened, reopened]

jobs:
  update-backlog-ticket:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract Backlog Issue Key
        id: extract-issue-key
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          # Extract Backlog issue key (e.g., PROJECT-123) from PR title
          issue_key=$(echo "$PR_TITLE" | grep -oE '[A-Z]+-[0-9]+')
          echo "Extracted Issue Key: $issue_key"
          echo "issue_key=$issue_key" >> $GITHUB_OUTPUT

      # Comment on Backlog Ticket (on PR creation)
      - name: Comment on Backlog Ticket (on PR creation)
        if: ${{ github.event.action == 'opened'}}
        env:
          BACKLOG_API_KEY: ${{ secrets.BACKLOG_API_KEY }}
          BACKLOG_ISSUE_KEY: ${{ steps.extract-issue-key.outputs.issue_key }}
        run: |
          PR_URL="${{ github.event.pull_request.html_url }}"
          PR_TITLE="${{ github.event.pull_request.title }}"
          COMMENT="Pull Request Created: [$PR_TITLE]($PR_URL)"
          curl -X POST \
            -H "Authorization: Bearer $BACKLOG_API_KEY" \
            -H "Content-Type: application/json" \
            -d "{\"content\": \"$COMMENT\"}" \
            "https://kietdo.backlog.com/api/v2/issues/${BACKLOG_ISSUE_KEY}/comments"

      # Update Backlog Issue Status
      - name: Update Backlog Issue Status
        if: steps.extract-issue-key.outputs.issue_key != '' && github.event.pull_request.merged == true
        env:
          BACKLOG_API_KEY: ${{ secrets.BACKLOG_API_KEY }}
          BACKLOG_ISSUE_KEY: ${{ steps.extract-issue-key.outputs.issue_key }}
        run: |
          # Assuming status ID 3 represents "Resolved" - adjust as needed
          resolved_status_id=3
          
          curl -X PATCH \
            "https://kietdo.backlog.com/api/v2/issues/${BACKLOG_ISSUE_KEY}?apiKey=${BACKLOG_API_KEY}" \
            -H "Content-Type: application/json" \
            -d "{
              \"statusId\": ${resolved_status_id}
            }" 