name: Backlog Issue Status Update

on:
  pull_request:
    types: [closed, opened, reopened]

jobs:
  update-backlog-ticket:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract Backlog Issue Key
        id: extract-issue-key
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          # Extract Backlog issue key (e.g., PROJECT-123) from PR title
          issue_key=$(echo "$PR_TITLE" | grep -oE '[A-Z]+-[0-9]+')
          echo "Extracted Issue Key: $issue_key"
          echo "issue_key=$issue_key" >> $GITHUB_OUTPUT

      # Comment on Backlog Ticket (on PR creation)
      - name: Comment on Backlog Ticket (on PR creation)
        # if: ${{ github.event.action == 'opened' || github.event.action == 'reopened' }}
        env:
          BACKLOG_API_KEY: ${{ secrets.BACKLOG_API_KEY }}
          BACKLOG_ISSUE_KEY: ${{ steps.extract-issue-key.outputs.issue_key }}
        run: |
          PR_URL="${{ github.event.pull_request.html_url }}"
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"
          PR_MERGE_BY="${{ github.event.pull_request.merged_by.login }}"
          PR_CLOSE_BY="${{ github.event.pull_request.closed_by.login }}"

          if [ "${{ github.event.pull_request.merged }}" == "true" ]; then
            COMMENT="Pull Request Merged: [$PR_TITLE]($PR_URL) by $PR_MERGE_BY"
          elif [ "${{ github.event.action }}" == "closed" ]; then
            COMMENT="Pull Request Closed: [$PR_TITLE]($PR_URL) by $PR_CLOSE_BY"
          else
            COMMENT="Pull Request Created: [$PR_TITLE]($PR_URL) by $PR_AUTHOR"
          fi
          curl -X POST \
            -H "Content-Type: application/json" \
            -d "{\"content\": \"$COMMENT\"}" \
            "https://kietdo.backlog.com/api/v2/issues/${BACKLOG_ISSUE_KEY}/comments?apiKey=${BACKLOG_API_KEY}"

      # Update Backlog Issue Status
      - name: Update Backlog Issue Status
        if: steps.extract-issue-key.outputs.issue_key != '' && ( github.event.action == 'closed' || github.event.pull_request.merged == true )
        env:
          BACKLOG_API_KEY: ${{ secrets.BACKLOG_API_KEY }}
          BACKLOG_ISSUE_KEY: ${{ steps.extract-issue-key.outputs.issue_key }}
        run: |
          # Assuming status ID 3 represents "Resolved" - adjust as needed
          resolved_status_id=3
          
          curl -X PATCH \
            "https://kietdo.backlog.com/api/v2/issues/${BACKLOG_ISSUE_KEY}?apiKey=${BACKLOG_API_KEY}" \
            -H "Content-Type: application/json" \
            -d "{
              \"statusId\": ${resolved_status_id}
            }" 